#!/bin/bash
install_to="${PREFIX:-$HOME}"
working_dir="$(pwd)"
scripts_dir=$install_to/bin
confdb="conf.db"

install_oh_my_zsh() {
    echo "configure-machine: installing oh-my-zsh"
    curl -L http://install.ohmyz.sh | sh
}

install_vim_dir() {
    echo "configure-machine: creating .vim directory"
    mkdir "$install_to/.vim"
    tar -xzf vim/vimdir.tar.gz -C $install_to/.vim --strip-components=1
}

create_dirs() {
    [[ ! -d "$scripts_dir" ]] && mkdir -p "$scripts_dir"
    [[ ! -d "$install_to/.vim" ]] && install_vim_dir
    [[ ! -d "$install_to/.oh-my-zsh" ]] && install_oh_my_zsh
}

parse_args() {
    for arg in "$@"
    do
        case $arg in
            --vim-dir)
                install_vim_dir
                ;;

            --oh-my-zsh)
                install_oh_my_zsh
                ;;
        esac
    done
}

link_files() {
    sqlite3 "$confdb" "select file, destination from file_locations" |\
        while read line;
        do
            file="$working_dir/$(echo $line | cut -d'|' -f1)"
            destination="$install_to/$(echo $line | cut -d'|' -f2)"
            if [[ -f "$file" && ! "$file" -ef "$destination" ]];
            then
                echo "configure-machine: linking $file to $destination"
                ln -f "$file" "$destination"
            elif [[ -n "$file" ]];
            then
                echo "configure-machine: $file already linked to $destination"
            fi
        done
}

parse_args
create_dirs
link_files
