#!/bin/zsh
#
if [[ "$(uname -s)" == "Darwin" ]];
then
    alias bd="brew doctor"
    alias bi="brew install"
    alias bs="brew search"
    alias bu="brew update"
    alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
    alias -g seid="sed -i ''"
fi

alias gc="git commit"
alias gcl="git clone"
alias gs="git status"

alias 40love="python -m SimpleHTTPServer &"
alias swag='eval sudo $(fc -l -1 | sed -E "s/[0-9]+[ ]*(.)/\1/")'
alias tmux="tmux -2"

alias v="vim"
alias vrc="vim ~/.vimrc"
alias zrc="vim ~/.zshrc"
alias emacs="vim"

if which vimcat &>> /dev/null;
then
    alias less="$PAGER"
    alias zless="$PAGER"
    alias vimcat="vimcat -c 'hi Normal ctermbg=none'"
    alias vc="vimcat"
    alias vcat="vimcat"
fi

# Linux specific
alias hc="herbstclient"
alias startx="ssh-agent startx"
alias turf="tabbed -c surf -e"
alias trux="tabbed -c urxvtc -embed"
alias thura="tabbed zathura -e"

# spelling probz
alias -g lsit="list"
alias bim="vim"
