# vim: set filetype=sh :
# Normally vim chooses the filetype zsh, which I find has inferior highlighing

ZSH=$HOME/.oh-my-zsh
DISABLE_AUTO_UPDATE="true"
plugins=(git mercurial)

if [[ "$TERM" == "linux" ]]; then
    # we're in the console
    ZSH_THEME="jveld-minimal"
else
    ZSH_THEME="jveld"
fi

source $ZSH/oh-my-zsh.sh
export EDITOR=vim
export PATH=/usr/bin:/usr/local/bin:~/bin

for config_file ($HOME/.zshrc-*);
do
    source $config_file
done
